---
title: "Mapa Dinámico, Estadísticas policiales en Costa Rica"
author: "Ana Guevara"
date: 2021-02-02T21:13:14-05:00
categories: ["R"]
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


# Estadísticas por Delito, Estadísticas por Género de la Victima:

```{r, echo=FALSE, warning=FALSE, results='hide', message=FALSE}
setwd("C:/Users/anagu/OneDrive/Documentos/TEC/SemestreII2020/SIG/sig-proyecto2-ChesGuev99")

library(sf)
library(dplyr)
library(leaflet)
library(leafpop)
library(RColorBrewer)
library(mapview)


puntosCR <- st_read("DistritosEdited.shp")
breaks = c(0,3,4,5)



# TIPO DE CRIMEN
mapview::mapview(puntosCR, alpha.regions = 10, col.regions = palette.colors(palette = 'Set3'), map.types = c('CartoDB.DarkMatter','CartoDB.Positron') , 
                 layer.name= 'Tipo De Crimen', zcol = "estadstica" ,
  popup = popupTable(puntosCR, zcol=c("NOM_PROV","NOM_CANT","NOM_DIST", 'COD_DIST',
  'estadstica', 'estadsti_1', 'estadsti_2', 'estadsti_3', 'estadsti_4'))) +

# Victima
  mapview::mapview(puntosCR, alpha.regions = 10, col.regions = palette.colors(palette = 'Accent'), map.types = c('CartoDB.DarkMatter','CartoDB.Positron') , 
                   layer.name= 'Victima', zcol = "estadsti_1" ,
                   popup = popupTable(puntosCR, zcol=c("NOM_PROV","NOM_CANT","NOM_DIST", 'COD_DIST',
                                                       'estadstica', 'estadsti_1', 'estadsti_2', 'estadsti_3', 'estadsti_4'))) +
# Edad
  mapview::mapview(puntosCR, alpha.regions = 10, map.types = c('CartoDB.DarkMatter','CartoDB.Positron') , 
                   layer.name= 'Edad', zcol = "estadsti_2" ,
                   popup = popupTable(puntosCR, zcol=c("NOM_PROV","NOM_CANT","NOM_DIST", 'COD_DIST',
                                                       'estadstica', 'estadsti_1', 'estadsti_2', 'estadsti_3', 'estadsti_4'))) +
# Genero
  mapview::mapview(puntosCR, alpha.regions = 10, col.regions = c('khaki','violetred', 'skyblue3'), map.types = c('CartoDB.DarkMatter','CartoDB.Positron') , 
                   layer.name= 'Género', zcol = "estadsti_3" ,
                   popup = popupTable(puntosCR, zcol=c("NOM_PROV","NOM_CANT","NOM_DIST", 'COD_DIST',
                                                       'estadstica', 'estadsti_1', 'estadsti_2', 'estadsti_3', 'estadsti_4'))) +
# Nacionalidad
  mapview::mapview(puntosCR, alpha.regions = 10, col.regions = brewer.pal(10, 'Dark2'), map.types = c('CartoDB.DarkMatter','CartoDB.Positron') , 
                   layer.name= 'Nacionalidad', zcol = "estadsti_4" ,
                   popup = popupTable(puntosCR, zcol=c("NOM_PROV","NOM_CANT","NOM_DIST", 'COD_DIST',
                                                       'estadstica', 'estadsti_1', 'estadsti_2', 'estadsti_3', 'estadsti_4'))) 


#print(puntosCR)


```